name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 07May2002@
          POSTGRES_DB: simple_bank
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U root -d simple_bank"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_DRIVER: postgres
      DB_SOURCE: postgres://root:07May2002@@localhost:5433/simple_bank?sslmode=disable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            if pg_isready -h localhost -p 5433 -U root -d simple_bank; then
              echo "Postgres is ready"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 3
          done
          echo "Postgres failed to start in time"
          exit 1

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run DB migrations
        run: |
          migrate -path db/migration -database "$DB_SOURCE" -verbose up

      - name: Run tests
        run: go test -v -cover ./...

